apiVersion: v1
kind: Service
metadata:
  name: travel-mlops-api

spec:
  type: LoadBalancer

  selector:
    app: travel-mlops-api

  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000